### PR TITLE
test1

### PR DESCRIPTION
**Pull request by wudicaox**
Tracked-On: OAM-66923
Signed-off-by: wudicaox <wudix.cao@intel.com>

### CODE REVIEW

**Review by 745631453 — APPROVED** [review]
ok

**Review by wudicaox — COMMENTED** [review]
PR integrated into 'preintegration' builder



More details, logs, and binaries: /absp-wudicaox_test/builders/for_integration_tests_android_github-preintegration/builds/17

Done by "Cao, WudiX" <wudix.cao@intel.com>

**Review by wudicaox — COMMENTED** [review]
PR integrated into 'premerge' builder



More details, logs, and binaries: /absp-wudicaox_test/builders/for_integration_tests_android_github-premerge/builds/8

Done by "Cao, WudiX" <wudix.cao@intel.com>

**Review by wudicaox — COMMENTED** [review]
PR integrated into 'preintegration' builder



More details, logs, and binaries: /absp-wudicaox_test/builders/for_integration_tests_android_github-preintegration/builds/20

Done by "Cao, WudiX" <wudix.cao@intel.com>

**Review by wudicaox — COMMENTED** [review]
PR integrated into 'premerge' builder



More details, logs, and binaries: /absp-wudicaox_test/builders/for_integration_tests_android_github-premerge/builds/10

Done by "Cao, WudiX" <wudix.cao@intel.com>

**Review by wudicaox — COMMENTED** [review]
PR integrated into 'preintegration' builder



More details, logs, and binaries: /absp-wudicaox_test/builders/for_integration_tests_android_github-preintegration/builds/23

Done by "Cao, WudiX" <wudix.cao@intel.com>

**Review by wudicaox — COMMENTED** [review]
PR integrated into 'premerge' builder



More details, logs, and binaries: /absp-wudicaox_test/builders/for_integration_tests_android_github-premerge/builds/12

Done by "Cao, WudiX" <wudix.cao@intel.com>

**Review by wudicaox — COMMENTED** [review]
PR integrated into 'preintegration' builder



More details, logs, and binaries: /absp-wudicaox_test/builders/for_integration_tests_android_github-preintegration/builds/26

Done by "Cao, WudiX" <wudix.cao@intel.com>

**Review by wudicaox — COMMENTED** [review]
PR integrated into 'premerge' builder



More details, logs, and binaries: /absp-wudicaox_test/builders/for_integration_tests_android_github-premerge/builds/15

Done by "Cao, WudiX" <wudix.cao@intel.com>

**Review by wudicaox — COMMENTED** [review]
PR integrated into 'preintegration' builder



More details, logs, and binaries: /absp-wudicaox_test/builders/for_integration_tests_android_github-preintegration/builds/29

Done by "Cao, WudiX" <wudix.cao@intel.com>

**Review by wudicaox — COMMENTED** [review]
PR integrated into 'premerge' builder



More details, logs, and binaries: /absp-wudicaox_test/builders/for_integration_tests_android_github-premerge/builds/18

Done by "Cao, WudiX" <wudix.cao@intel.com>

**Review by wudicaox — COMMENTED** [review]
PR integrated into 'preintegration' builder



More details, logs, and binaries: /absp-wudicaox_test/builders/for_integration_tests_android_github-preintegration/builds/32

Done by "Cao, WudiX" <wudix.cao@intel.com>

**Review by wudicaox — COMMENTED** [review]
PR integrated into 'premerge' builder



More details, logs, and binaries: /absp-wudicaox_test/builders/for_integration_tests_android_github-premerge/builds/21

Done by "Cao, WudiX" <wudix.cao@intel.com>

**Review by wudicaox — COMMENTED** [review]
PR integrated into 'preintegration' builder



More details, logs, and binaries: /absp-wudicaox_test/builders/for_integration_tests_android_github-preintegration/builds/35

Done by "Cao, WudiX" <wudix.cao@intel.com>

**Review by wudicaox — COMMENTED** [review]
PR integrated into 'premerge' builder



More details, logs, and binaries: /absp-wudicaox_test/builders/for_integration_tests_android_github-premerge/builds/25

Done by "Cao, WudiX" <wudix.cao@intel.com>

**Review by wudicaox — COMMENTED** [review]
PR integrated into 'preintegration' builder



More details, logs, and binaries: /absp-wudicaox_test/builders/for_integration_tests_android_github-preintegration/builds/38

Done by "Cao, WudiX" <wudix.cao@intel.com>

**Review by wudicaox — COMMENTED** [review]
PR integrated into 'premerge' builder



More details, logs, and binaries: /absp-wudicaox_test/builders/for_integration_tests_android_github-premerge/builds/27

Done by "Cao, WudiX" <wudix.cao@intel.com>

**Review by wudicaox — COMMENTED** [review]
PR integrated into 'preintegration' builder



More details, logs, and binaries: /absp-wudicaox_test/builders/for_integration_tests_android_github-preintegration/builds/41

Done by "Cao, WudiX" <wudix.cao@intel.com>

**Review by wudicaox — COMMENTED** [review]
PR integrated into 'premerge' builder



More details, logs, and binaries: /absp-wudicaox_test/builders/for_integration_tests_android_github-premerge/builds/31

Done by "Cao, WudiX" <wudix.cao@intel.com>

**Review by wudicaox — COMMENTED** [review]
PR integrated into 'preintegration' builder



More details, logs, and binaries: /absp-wudicaox_test/builders/for_integration_tests_android_github-preintegration/builds/44

Done by "Cao, WudiX" <wudix.cao@intel.com>

**Review by wudicaox — COMMENTED** [review]
PR integrated into 'premerge' builder



More details, logs, and binaries: /absp-wudicaox_test/builders/for_integration_tests_android_github-premerge/builds/33

Done by "Cao, WudiX" <wudix.cao@intel.com>

**Review by wudicaox — COMMENTED** [review]
PR integrated into 'preintegration' builder



More details, logs, and binaries: /absp-wudicaox_test/builders/for_integration_tests_android_github-preintegration/builds/47

Done by "Cao, WudiX" <wudix.cao@intel.com>

**Review by wudicaox — COMMENTED** [review]
PR integrated into 'premerge' builder



More details, logs, and binaries: /absp-wudicaox_test/builders/for_integration_tests_android_github-premerge/builds/38

Done by "Cao, WudiX" <wudix.cao@intel.com>

**Review by wudicaox — COMMENTED** [review]
PR integrated into 'preintegration' builder



More details, logs, and binaries: /absp-wudicaox_test/builders/for_integration_tests_android_github-preintegration/builds/50

Done by "Cao, WudiX" <wudix.cao@intel.com>

**Review by wudicaox — COMMENTED** [review]
PR integrated into 'premerge' builder



More details, logs, and binaries: /absp-wudicaox_test/builders/for_integration_tests_android_github-premerge/builds/39

Done by "Cao, WudiX" <wudix.cao@intel.com>

**Review by wudicaox — COMMENTED** [review]
PR integrated into 'preintegration' builder



More details, logs, and binaries: /absp-wudicaox_test/builders/for_integration_tests_android_github-preintegration/builds/53

Done by "Cao, WudiX" <wudix.cao@intel.com>

**Review by wudicaox — COMMENTED** [review]
PR integrated into 'premerge' builder



More details, logs, and binaries: /absp-wudicaox_test/builders/for_integration_tests_android_github-premerge/builds/43

Done by "Cao, WudiX" <wudix.cao@intel.com>

**Review by wudicaox — COMMENTED** [review]
PR integrated into 'preintegration' builder



More details, logs, and binaries: /absp-wudicaox_test/builders/for_integration_tests_android_github-preintegration/builds/56

Done by "Cao, WudiX" <wudix.cao@intel.com>

**Review by wudicaox — COMMENTED** [review]
PR integrated into 'premerge' builder



More details, logs, and binaries: /absp-wudicaox_test/builders/for_integration_tests_android_github-premerge/builds/47

Done by "Cao, WudiX" <wudix.cao@intel.com>

**Review by wudicaox — COMMENTED** [review]
PR integrated into 'preintegration' builder



More details, logs, and binaries: /absp-wudicaox_test/builders/for_integration_tests_android_github-preintegration/builds/59

Done by "Cao, WudiX" <wudix.cao@intel.com>

**Review by wudicaox — COMMENTED** [review]
PR integrated into 'premerge' builder



More details, logs, and binaries: /absp-wudicaox_test/builders/for_integration_tests_android_github-premerge/builds/48

Done by "Cao, WudiX" <wudix.cao@intel.com>

**Review by wudicaox — COMMENTED** [review]
PR integrated into 'preintegration' builder



More details, logs, and binaries: /absp-wudicaox_test/builders/for_integration_tests_android_github-preintegration/builds/62

Done by "Cao, WudiX" <wudix.cao@intel.com>

**Review by wudicaox — COMMENTED** [review]
PR integrated into 'premerge' builder



More details, logs, and binaries: /absp-wudicaox_test/builders/for_integration_tests_android_github-premerge/builds/51

Done by "Cao, WudiX" <wudix.cao@intel.com>

**Review by wudicaox — COMMENTED** [review]
PR integrated into 'preintegration' builder



More details, logs, and binaries: /absp-wudicaox_test/builders/for_integration_tests_android_github-preintegration/builds/65

Done by "Cao, WudiX" <wudix.cao@intel.com>

**Review by wudicaox — COMMENTED** [review]
PR integrated into 'premerge' builder



More details, logs, and binaries: /absp-wudicaox_test/builders/for_integration_tests_android_github-premerge/builds/54

Done by "Cao, WudiX" <wudix.cao@intel.com>

**Review by wudicaox — COMMENTED** [review]
PR integrated into 'preintegration' builder



More details, logs, and binaries: /absp-wudicaox_test/builders/for_integration_tests_android_github-preintegration/builds/68

Done by "Cao, WudiX" <wudix.cao@intel.com>

**Review by wudicaox — COMMENTED** [review]
PR integrated into 'premerge' builder



More details, logs, and binaries: /absp-wudicaox_test/builders/for_integration_tests_android_github-premerge/builds/58

Done by "Cao, WudiX" <wudix.cao@intel.com>

**Review by wudicaox — COMMENTED** [review]
PR integrated into 'preintegration' builder



More details, logs, and binaries: /absp-wudicaox_test/builders/for_integration_tests_android_github-preintegration/builds/71

Done by "Cao, WudiX" <wudix.cao@intel.com>

**Review by wudicaox — COMMENTED** [review]
PR integrated into 'premerge' builder



More details, logs, and binaries: /absp-wudicaox_test/builders/for_integration_tests_android_github-premerge/builds/60

Done by "Cao, WudiX" <wudix.cao@intel.com>

**Review by wudicaox — COMMENTED** [review]
PR integrated into 'preintegration' builder



More details, logs, and binaries: /absp-wudicaox_test/builders/for_integration_tests_android_github-preintegration/builds/74

Done by "Cao, WudiX" <wudix.cao@intel.com>

**Review by wudicaox — COMMENTED** [review]
PR integrated into 'premerge' builder



More details, logs, and binaries: /absp-wudicaox_test/builders/for_integration_tests_android_github-premerge/builds/63

Done by "Cao, WudiX" <wudix.cao@intel.com>

**Review by wudicaox — COMMENTED** [review]
PR integrated into 'preintegration' builder



More details, logs, and binaries: /absp-wudicaox_test/builders/for_integration_tests_android_github-preintegration/builds/77

Done by "Cao, WudiX" <wudix.cao@intel.com>

**Review by wudicaox — COMMENTED** [review]
PR integrated into 'premerge' builder



More details, logs, and binaries: /absp-wudicaox_test/builders/for_integration_tests_android_github-premerge/builds/67

Done by "Cao, WudiX" <wudix.cao@intel.com>

**Review by wudicaox — COMMENTED** [review]
PR integrated into 'preintegration' builder



More details, logs, and binaries: /absp-wudicaox_test/builders/for_integration_tests_android_github-preintegration/builds/80

Done by "Cao, WudiX" <wudix.cao@intel.com>

**Review by wudicaox — COMMENTED** [review]
PR integrated into 'premerge' builder



More details, logs, and binaries: /absp-wudicaox_test/builders/for_integration_tests_android_github-premerge/builds/69

Done by "Cao, WudiX" <wudix.cao@intel.com>

**Review by wudicaox — COMMENTED** [review]
Failure when executing preintegration builder

FAILURE:Trigger Builds Triggered: build-for_integration_tests - r1 (r1_target1) - extra, build-for_integration_tests - r1 (r2_target1), build-for_integration_tests - r1 (r2_target2)

More details, logs, and binaries: /absp-wudicaox_test/builders/for_integration_tests_android_github-preintegration/builds/83

**Review by wudicaox — COMMENTED** [review]
Failure when executing preintegration builder

FAILURE:Trigger Builds Triggered: build-for_integration_tests - r1 (r1_target1) - extra, build-for_integration_tests - r1 (r2_target1), build-for_integration_tests - r1 (r2_target2)

More details, logs, and binaries: /absp-wudicaox_test/builders/for_integration_tests_android_github-preintegration/builds/86

**Review by wudicaox — COMMENTED** [review]
Failure when executing preintegration builder

FAILURE:Trigger Builds Triggered: build-for_integration_tests - r1 (r1_target1) - extra, build-for_integration_tests - r1 (r2_target1), build-for_integration_tests - r1 (r2_target2)

More details, logs, and binaries: /absp-wudicaox_test/builders/for_integration_tests_android_github-preintegration/builds/87

**Review by wudicaox — COMMENTED** [review]
Failure when executing preintegration builder

FAILURE:Start external build cancelled

More details, logs, and binaries: /absp-wudicaox_test/builders/for_integration_tests_android_github-preintegration/builds/88

**Review by wudicaox — COMMENTED** [review]
PR integrated into 'preintegration' builder



More details, logs, and binaries: /absp-wudicaox_test/builders/for_integration_tests_android_github-preintegration/builds/89

Done by "Cao, WudiX" <wudix.cao@intel.com>

**Review by wudicaox — COMMENTED** [review]
PR integrated into 'premerge' builder



More details, logs, and binaries: /absp-wudicaox_test/builders/for_integration_tests_android_github-premerge/builds/72

Done by "Cao, WudiX" <wudix.cao@intel.com>

**Review by wudicaox — COMMENTED** [review]
Failure when executing preintegration builder

FAILURE:Trigger Builds Triggered: build-for_integration_tests - r1 (r1_target1) - extra, build-for_integration_tests - r1 (r2_target1), build-for_integration_tests - r1 (r2_target2)

More details, logs, and binaries: /absp-wudicaox_test/builders/for_integration_tests_android_github-preintegration/builds/90

**Review by wudicaox — COMMENTED** [review]
Failure when executing preintegration builder

FAILURE:Trigger Builds Triggered: build-for_integration_tests - r1 (r1_target1) - extra, build-for_integration_tests - r1 (r2_target1), build-for_integration_tests - r1 (r2_target2)

More details, logs, and binaries: /absp-wudicaox_test/builders/for_integration_tests_android_github-preintegration/builds/91

**Review by wudicaox — COMMENTED** [review]
Failure when executing preintegration builder

FAILURE:Trigger Builds Triggered: build-for_integration_tests - r1 (r1_target1) - extra, build-for_integration_tests - r1 (r2_target1), build-for_integration_tests - r1 (r2_target2)

More details, logs, and binaries: /absp-wudicaox_test/builders/for_integration_tests_android_github-preintegration/builds/98

**Review by wudicaox — COMMENTED** [review]
Failure when executing preintegration builder

FAILURE:Trigger Builds Triggered: build-for_integration_tests - r1 (r1_target1) - extra, build-for_integration_tests - r1 (r2_target1), build-for_integration_tests - r1 (r2_target2)

More details, logs, and binaries: /absp-wudicaox_test/builders/for_integration_tests_android_github-preintegration/builds/101

**Review by wudicaox — COMMENTED** [review]
Failure when executing preintegration builder

FAILURE:Trigger Builds Triggered: build-for_integration_tests - r1 (r1_target1) - extra, build-for_integration_tests - r1 (r2_target1), build-for_integration_tests - r1 (r2_target2)

More details, logs, and binaries: /absp-wudicaox_test/builders/for_integration_tests_android_github-preintegration/builds/102

**Review by wudicaox — COMMENTED** [review]
Failure when executing preintegration builder

FAILURE:Trigger Builds Triggered: build-for_integration_tests - r1 (r1_target1) - extra, build-for_integration_tests - r1 (r2_target1), build-for_integration_tests - r1 (r2_target2)

More details, logs, and binaries: /absp-wudicaox_test/builders/for_integration_tests_android_github-preintegration/builds/103

**Review by wudicaox — COMMENTED** [review]
Failure when executing preintegration builder

FAILURE:Trigger Builds cancelled

More details, logs, and binaries: /absp-wudicaox_test/builders/for_integration_tests_android_github-preintegration/builds/104

**Review by wudicaox — COMMENTED** [review]
PR integrated into 'preintegration' builder



More details, logs, and binaries: /absp-wudicaox_test/builders/for_integration_tests_android_github-preintegration/builds/105

Done by "Cao, WudiX" <wudix.cao@intel.com>

**Review by wudicaox — COMMENTED** [review]
PR integrated into 'premerge' builder



More details, logs, and binaries: /absp-wudicaox_test/builders/for_integration_tests_android_github-premerge/builds/73

Done by "Cao, WudiX" <wudix.cao@intel.com>

**Review by wudicaox — COMMENTED** [review]
Failure when executing preintegration builder

FAILURE:Trigger Builds Triggered: build-for_integration_tests - r1 (r1_target1) - extra, build-for_integration_tests - r1 (r2_target1), build-for_integration_tests - r1 (r2_target2)

More details, logs, and binaries: /absp-wudicaox_test/builders/for_integration_tests_android_github-preintegration/builds/108

**Review by wudicaox — COMMENTED** [review]
PR integrated into 'preintegration' builder



More details, logs, and binaries: /absp-wudicaox_test/builders/for_integration_tests_android_github-preintegration/builds/111

Done by "Cao, WudiX" <wudix.cao@intel.com>

**Review by wudicaox — COMMENTED** [review]
PR integrated into 'premerge' builder



More details, logs, and binaries: /absp-wudicaox_test/builders/for_integration_tests_android_github-premerge/builds/76

Done by "Cao, WudiX" <wudix.cao@intel.com>

**Review by wudicaox — COMMENTED** [review]
PR integrated into 'preintegration' builder



More details, logs, and binaries: /absp-wudicaox_test/builders/for_integration_tests_android_github-preintegration/builds/114

Done by "Cao, WudiX" <wudix.cao@intel.com>

**Review by wudicaox — COMMENTED** [review]
PR integrated into 'premerge' builder



More details, logs, and binaries: /absp-wudicaox_test/builders/for_integration_tests_android_github-premerge/builds/81

Done by "Cao, WudiX" <wudix.cao@intel.com>

**Review by wudicaox — COMMENTED** [review]
PR integrated into 'preintegration' builder



More details, logs, and binaries: /absp-wudicaox_test/builders/for_integration_tests_android_github-preintegration/builds/117

Done by "Cao, WudiX" <wudix.cao@intel.com>

**Review by wudicaox — COMMENTED** [review]
PR integrated into 'premerge' builder



More details, logs, and binaries: /absp-wudicaox_test/builders/for_integration_tests_android_github-premerge/builds/82

Done by "Cao, WudiX" <wudix.cao@intel.com>

**Review by wudicaox — COMMENTED** [review]
PR integrated into 'preintegration' builder



More details, logs, and binaries: /absp-wudicaox_test/builders/for_integration_tests_android_github-preintegration/builds/120

Done by "Cao, WudiX" <wudix.cao@intel.com>

**Review by wudicaox — COMMENTED** [review]
PR integrated into 'premerge' builder



More details, logs, and binaries: /absp-wudicaox_test/builders/for_integration_tests_android_github-premerge/builds/87

Done by "Cao, WudiX" <wudix.cao@intel.com>

**Review by wudicaox — COMMENTED** [review]
PR integrated into 'preintegration' builder



More details, logs, and binaries: /absp-wudicaox_test/builders/for_integration_tests_android_github-preintegration/builds/123

Done by "Cao, WudiX" <wudix.cao@intel.com>

**Review by wudicaox — COMMENTED** [review]
PR integrated into 'premerge' builder



More details, logs, and binaries: /absp-wudicaox_test/builders/for_integration_tests_android_github-premerge/builds/89

Done by "Cao, WudiX" <wudix.cao@intel.com>

**Review by wudicaox — COMMENTED** [review]
PR integrated into 'preintegration' builder



More details, logs, and binaries: /absp-wudicaox_test/builders/for_integration_tests_android_github-preintegration/builds/126

Done by "Cao, WudiX" <wudix.cao@intel.com>

**Review by wudicaox — COMMENTED** [review]
PR integrated into 'premerge' builder



More details, logs, and binaries: /absp-wudicaox_test/builders/for_integration_tests_android_github-premerge/builds/91

Done by "Cao, WudiX" <wudix.cao@intel.com>

**Review by wudicaox — COMMENTED** [review]
PR integrated into 'preintegration' builder



More details, logs, and binaries: /absp-wudicaox_test/builders/for_integration_tests_android_github-preintegration/builds/129

Done by "Cao, WudiX" <wudix.cao@intel.com>

**Review by wudicaox — COMMENTED** [review]
PR integrated into 'premerge' builder



More details, logs, and binaries: /absp-wudicaox_test/builders/for_integration_tests_android_github-premerge/builds/94

Done by "Cao, WudiX" <wudix.cao@intel.com>

**Pull request closed without merging**
