### PR TITLE
test2

### PR DESCRIPTION
**Pull request by wudicaox**
Tracked-On: OAM-66906
Signed-off-by: wudicaox <wudix.cao@intel.com>

### CODE REVIEW

**Review by 745631453 — APPROVED** [review]
ok

**Review by wudicaox — COMMENTED** [review]
PR integrated into 'preintegration' builder



More details, logs, and binaries: /absp-wudicaox_test/builders/for_integration_tests_android_github-preintegration/builds/18

Done by "Cao, WudiX" <wudix.cao@intel.com>

**Review by wudicaox — COMMENTED** [review]
PR integrated into 'premerge' builder



More details, logs, and binaries: /absp-wudicaox_test/builders/for_integration_tests_android_github-premerge/builds/6

Done by "Cao, WudiX" <wudix.cao@intel.com>

**Review by wudicaox — COMMENTED** [review]
PR integrated into 'preintegration' builder



More details, logs, and binaries: /absp-wudicaox_test/builders/for_integration_tests_android_github-preintegration/builds/21

Done by "Cao, WudiX" <wudix.cao@intel.com>

**Review by wudicaox — COMMENTED** [review]
PR integrated into 'premerge' builder



More details, logs, and binaries: /absp-wudicaox_test/builders/for_integration_tests_android_github-premerge/builds/11

Done by "Cao, WudiX" <wudix.cao@intel.com>

**Review by wudicaox — COMMENTED** [review]
PR integrated into 'preintegration' builder



More details, logs, and binaries: /absp-wudicaox_test/builders/for_integration_tests_android_github-preintegration/builds/24

Done by "Cao, WudiX" <wudix.cao@intel.com>

**Review by wudicaox — COMMENTED** [review]
PR integrated into 'premerge' builder



More details, logs, and binaries: /absp-wudicaox_test/builders/for_integration_tests_android_github-premerge/builds/13

Done by "Cao, WudiX" <wudix.cao@intel.com>

**Review by wudicaox — COMMENTED** [review]
PR integrated into 'preintegration' builder



More details, logs, and binaries: /absp-wudicaox_test/builders/for_integration_tests_android_github-preintegration/builds/27

Done by "Cao, WudiX" <wudix.cao@intel.com>

**Review by wudicaox — COMMENTED** [review]
PR integrated into 'premerge' builder



More details, logs, and binaries: /absp-wudicaox_test/builders/for_integration_tests_android_github-premerge/builds/17

Done by "Cao, WudiX" <wudix.cao@intel.com>

**Review by wudicaox — COMMENTED** [review]
PR integrated into 'preintegration' builder



More details, logs, and binaries: /absp-wudicaox_test/builders/for_integration_tests_android_github-preintegration/builds/30

Done by "Cao, WudiX" <wudix.cao@intel.com>

**Review by wudicaox — COMMENTED** [review]
PR integrated into 'premerge' builder



More details, logs, and binaries: /absp-wudicaox_test/builders/for_integration_tests_android_github-premerge/builds/20

Done by "Cao, WudiX" <wudix.cao@intel.com>

**Review by wudicaox — COMMENTED** [review]
PR integrated into 'preintegration' builder



More details, logs, and binaries: /absp-wudicaox_test/builders/for_integration_tests_android_github-preintegration/builds/33

Done by "Cao, WudiX" <wudix.cao@intel.com>

**Review by wudicaox — COMMENTED** [review]
PR integrated into 'premerge' builder



More details, logs, and binaries: /absp-wudicaox_test/builders/for_integration_tests_android_github-premerge/builds/22

Done by "Cao, WudiX" <wudix.cao@intel.com>

**Review by wudicaox — COMMENTED** [review]
PR integrated into 'preintegration' builder



More details, logs, and binaries: /absp-wudicaox_test/builders/for_integration_tests_android_github-preintegration/builds/36

Done by "Cao, WudiX" <wudix.cao@intel.com>

**Review by wudicaox — COMMENTED** [review]
PR integrated into 'premerge' builder



More details, logs, and binaries: /absp-wudicaox_test/builders/for_integration_tests_android_github-premerge/builds/24

Done by "Cao, WudiX" <wudix.cao@intel.com>

**Review by wudicaox — COMMENTED** [review]
PR integrated into 'preintegration' builder



More details, logs, and binaries: /absp-wudicaox_test/builders/for_integration_tests_android_github-preintegration/builds/39

Done by "Cao, WudiX" <wudix.cao@intel.com>

**Review by wudicaox — COMMENTED** [review]
PR integrated into 'premerge' builder



More details, logs, and binaries: /absp-wudicaox_test/builders/for_integration_tests_android_github-premerge/builds/29

Done by "Cao, WudiX" <wudix.cao@intel.com>

**Review by wudicaox — COMMENTED** [review]
PR integrated into 'preintegration' builder



More details, logs, and binaries: /absp-wudicaox_test/builders/for_integration_tests_android_github-preintegration/builds/42

Done by "Cao, WudiX" <wudix.cao@intel.com>

**Review by wudicaox — COMMENTED** [review]
PR integrated into 'premerge' builder



More details, logs, and binaries: /absp-wudicaox_test/builders/for_integration_tests_android_github-premerge/builds/30

Done by "Cao, WudiX" <wudix.cao@intel.com>

**Review by wudicaox — COMMENTED** [review]
PR integrated into 'preintegration' builder



More details, logs, and binaries: /absp-wudicaox_test/builders/for_integration_tests_android_github-preintegration/builds/45

Done by "Cao, WudiX" <wudix.cao@intel.com>

**Review by wudicaox — COMMENTED** [review]
PR integrated into 'premerge' builder



More details, logs, and binaries: /absp-wudicaox_test/builders/for_integration_tests_android_github-premerge/builds/34

Done by "Cao, WudiX" <wudix.cao@intel.com>

**Review by wudicaox — COMMENTED** [review]
PR integrated into 'preintegration' builder



More details, logs, and binaries: /absp-wudicaox_test/builders/for_integration_tests_android_github-preintegration/builds/48

Done by "Cao, WudiX" <wudix.cao@intel.com>

**Review by wudicaox — COMMENTED** [review]
PR integrated into 'premerge' builder



More details, logs, and binaries: /absp-wudicaox_test/builders/for_integration_tests_android_github-premerge/builds/36

Done by "Cao, WudiX" <wudix.cao@intel.com>

**Review by wudicaox — COMMENTED** [review]
PR integrated into 'preintegration' builder



More details, logs, and binaries: /absp-wudicaox_test/builders/for_integration_tests_android_github-preintegration/builds/51

Done by "Cao, WudiX" <wudix.cao@intel.com>

**Review by wudicaox — COMMENTED** [review]
PR integrated into 'premerge' builder



More details, logs, and binaries: /absp-wudicaox_test/builders/for_integration_tests_android_github-premerge/builds/40

Done by "Cao, WudiX" <wudix.cao@intel.com>

**Review by wudicaox — COMMENTED** [review]
PR integrated into 'preintegration' builder



More details, logs, and binaries: /absp-wudicaox_test/builders/for_integration_tests_android_github-preintegration/builds/54

Done by "Cao, WudiX" <wudix.cao@intel.com>

**Review by wudicaox — COMMENTED** [review]
PR integrated into 'premerge' builder



More details, logs, and binaries: /absp-wudicaox_test/builders/for_integration_tests_android_github-premerge/builds/44

Done by "Cao, WudiX" <wudix.cao@intel.com>

**Review by wudicaox — COMMENTED** [review]
PR integrated into 'preintegration' builder



More details, logs, and binaries: /absp-wudicaox_test/builders/for_integration_tests_android_github-preintegration/builds/57

Done by "Cao, WudiX" <wudix.cao@intel.com>

**Review by wudicaox — COMMENTED** [review]
PR integrated into 'premerge' builder



More details, logs, and binaries: /absp-wudicaox_test/builders/for_integration_tests_android_github-premerge/builds/46

Done by "Cao, WudiX" <wudix.cao@intel.com>

**Review by wudicaox — COMMENTED** [review]
PR integrated into 'preintegration' builder



More details, logs, and binaries: /absp-wudicaox_test/builders/for_integration_tests_android_github-preintegration/builds/60

Done by "Cao, WudiX" <wudix.cao@intel.com>

**Review by wudicaox — COMMENTED** [review]
PR integrated into 'premerge' builder



More details, logs, and binaries: /absp-wudicaox_test/builders/for_integration_tests_android_github-premerge/builds/49

Done by "Cao, WudiX" <wudix.cao@intel.com>

**Review by wudicaox — COMMENTED** [review]
PR integrated into 'preintegration' builder



More details, logs, and binaries: /absp-wudicaox_test/builders/for_integration_tests_android_github-preintegration/builds/63

Done by "Cao, WudiX" <wudix.cao@intel.com>

**Review by wudicaox — COMMENTED** [review]
PR integrated into 'premerge' builder



More details, logs, and binaries: /absp-wudicaox_test/builders/for_integration_tests_android_github-premerge/builds/52

Done by "Cao, WudiX" <wudix.cao@intel.com>

**Review by wudicaox — COMMENTED** [review]
PR integrated into 'preintegration' builder



More details, logs, and binaries: /absp-wudicaox_test/builders/for_integration_tests_android_github-preintegration/builds/66

Done by "Cao, WudiX" <wudix.cao@intel.com>

**Review by wudicaox — COMMENTED** [review]
PR integrated into 'premerge' builder



More details, logs, and binaries: /absp-wudicaox_test/builders/for_integration_tests_android_github-premerge/builds/56

Done by "Cao, WudiX" <wudix.cao@intel.com>

**Review by wudicaox — COMMENTED** [review]
PR integrated into 'preintegration' builder



More details, logs, and binaries: /absp-wudicaox_test/builders/for_integration_tests_android_github-preintegration/builds/69

Done by "Cao, WudiX" <wudix.cao@intel.com>

**Review by wudicaox — COMMENTED** [review]
PR integrated into 'premerge' builder



More details, logs, and binaries: /absp-wudicaox_test/builders/for_integration_tests_android_github-premerge/builds/59

Done by "Cao, WudiX" <wudix.cao@intel.com>

**Review by wudicaox — COMMENTED** [review]
PR integrated into 'preintegration' builder



More details, logs, and binaries: /absp-wudicaox_test/builders/for_integration_tests_android_github-preintegration/builds/72

Done by "Cao, WudiX" <wudix.cao@intel.com>

**Review by wudicaox — COMMENTED** [review]
PR integrated into 'premerge' builder



More details, logs, and binaries: /absp-wudicaox_test/builders/for_integration_tests_android_github-premerge/builds/61

Done by "Cao, WudiX" <wudix.cao@intel.com>

**Review by wudicaox — COMMENTED** [review]
PR integrated into 'preintegration' builder



More details, logs, and binaries: /absp-wudicaox_test/builders/for_integration_tests_android_github-preintegration/builds/75

Done by "Cao, WudiX" <wudix.cao@intel.com>

**Review by wudicaox — COMMENTED** [review]
PR integrated into 'premerge' builder



More details, logs, and binaries: /absp-wudicaox_test/builders/for_integration_tests_android_github-premerge/builds/64

Done by "Cao, WudiX" <wudix.cao@intel.com>

**Review by wudicaox — COMMENTED** [review]
PR integrated into 'preintegration' builder



More details, logs, and binaries: /absp-wudicaox_test/builders/for_integration_tests_android_github-preintegration/builds/78

Done by "Cao, WudiX" <wudix.cao@intel.com>

**Review by wudicaox — COMMENTED** [review]
PR integrated into 'premerge' builder



More details, logs, and binaries: /absp-wudicaox_test/builders/for_integration_tests_android_github-premerge/builds/66

Done by "Cao, WudiX" <wudix.cao@intel.com>

**Review by wudicaox — COMMENTED** [review]
PR integrated into 'preintegration' builder



More details, logs, and binaries: /absp-wudicaox_test/builders/for_integration_tests_android_github-preintegration/builds/81

Done by "Cao, WudiX" <wudix.cao@intel.com>

**Review by wudicaox — COMMENTED** [review]
PR integrated into 'premerge' builder



More details, logs, and binaries: /absp-wudicaox_test/builders/for_integration_tests_android_github-premerge/builds/70

Done by "Cao, WudiX" <wudix.cao@intel.com>

**Review by wudicaox — COMMENTED** [review]
Failure when executing preintegration builder

FAILURE:Trigger Builds Triggered: build-for_integration_tests - r1 (r1_target1) - extra, build-for_integration_tests - r1 (r2_target1), build-for_integration_tests - r1 (r2_target2)

More details, logs, and binaries: /absp-wudicaox_test/builders/for_integration_tests_android_github-preintegration/builds/84

**Review by wudicaox — COMMENTED** [review]
Failure when executing preintegration builder

FAILURE:Trigger Builds Triggered: build-for_integration_tests - r1 (r1_target1) - extra, build-for_integration_tests - r1 (r2_target1), build-for_integration_tests - r1 (r2_target2)

More details, logs, and binaries: /absp-wudicaox_test/builders/for_integration_tests_android_github-preintegration/builds/92

**Review by wudicaox — COMMENTED** [review]
Failure when executing preintegration builder

FAILURE:Trigger Builds Triggered: build-for_integration_tests - r1 (r1_target1) - extra, build-for_integration_tests - r1 (r2_target1), build-for_integration_tests - r1 (r2_target2)

More details, logs, and binaries: /absp-wudicaox_test/builders/for_integration_tests_android_github-preintegration/builds/99

**Review by wudicaox — COMMENTED** [review]
PR integrated into 'preintegration' builder



More details, logs, and binaries: /absp-wudicaox_test/builders/for_integration_tests_android_github-preintegration/builds/106

Done by "Cao, WudiX" <wudix.cao@intel.com>

**Review by wudicaox — COMMENTED** [review]
PR integrated into 'premerge' builder



More details, logs, and binaries: /absp-wudicaox_test/builders/for_integration_tests_android_github-premerge/builds/74

Done by "Cao, WudiX" <wudix.cao@intel.com>

**Review by wudicaox — COMMENTED** [review]
Failure when executing preintegration builder

FAILURE:Trigger Builds Triggered: build-for_integration_tests - r1 (r1_target1) - extra, build-for_integration_tests - r1 (r2_target1), build-for_integration_tests - r1 (r2_target2)

More details, logs, and binaries: /absp-wudicaox_test/builders/for_integration_tests_android_github-preintegration/builds/109

**Review by wudicaox — COMMENTED** [review]
PR integrated into 'preintegration' builder



More details, logs, and binaries: /absp-wudicaox_test/builders/for_integration_tests_android_github-preintegration/builds/112

Done by "Cao, WudiX" <wudix.cao@intel.com>

**Review by wudicaox — COMMENTED** [review]
PR integrated into 'premerge' builder



More details, logs, and binaries: /absp-wudicaox_test/builders/for_integration_tests_android_github-premerge/builds/77

Done by "Cao, WudiX" <wudix.cao@intel.com>

**Review by wudicaox — COMMENTED** [review]
PR integrated into 'preintegration' builder



More details, logs, and binaries: /absp-wudicaox_test/builders/for_integration_tests_android_github-preintegration/builds/115

Done by "Cao, WudiX" <wudix.cao@intel.com>

**Review by wudicaox — COMMENTED** [review]
PR integrated into 'premerge' builder



More details, logs, and binaries: /absp-wudicaox_test/builders/for_integration_tests_android_github-premerge/builds/79

Done by "Cao, WudiX" <wudix.cao@intel.com>

**Review by wudicaox — COMMENTED** [review]
PR integrated into 'preintegration' builder



More details, logs, and binaries: /absp-wudicaox_test/builders/for_integration_tests_android_github-preintegration/builds/118

Done by "Cao, WudiX" <wudix.cao@intel.com>

**Review by wudicaox — COMMENTED** [review]
PR integrated into 'premerge' builder



More details, logs, and binaries: /absp-wudicaox_test/builders/for_integration_tests_android_github-premerge/builds/83

Done by "Cao, WudiX" <wudix.cao@intel.com>

**Review by wudicaox — COMMENTED** [review]
PR integrated into 'preintegration' builder



More details, logs, and binaries: /absp-wudicaox_test/builders/for_integration_tests_android_github-preintegration/builds/121

Done by "Cao, WudiX" <wudix.cao@intel.com>

**Review by wudicaox — COMMENTED** [review]
PR integrated into 'premerge' builder



More details, logs, and binaries: /absp-wudicaox_test/builders/for_integration_tests_android_github-premerge/builds/85

Done by "Cao, WudiX" <wudix.cao@intel.com>

**Review by wudicaox — COMMENTED** [review]
PR integrated into 'preintegration' builder



More details, logs, and binaries: /absp-wudicaox_test/builders/for_integration_tests_android_github-preintegration/builds/124

Done by "Cao, WudiX" <wudix.cao@intel.com>

**Review by wudicaox — COMMENTED** [review]
PR integrated into 'premerge' builder



More details, logs, and binaries: /absp-wudicaox_test/builders/for_integration_tests_android_github-premerge/builds/88

Done by "Cao, WudiX" <wudix.cao@intel.com>

**Review by wudicaox — COMMENTED** [review]
PR integrated into 'preintegration' builder



More details, logs, and binaries: /absp-wudicaox_test/builders/for_integration_tests_android_github-preintegration/builds/127

Done by "Cao, WudiX" <wudix.cao@intel.com>

**Review by wudicaox — COMMENTED** [review]
PR integrated into 'premerge' builder



More details, logs, and binaries: /absp-wudicaox_test/builders/for_integration_tests_android_github-premerge/builds/92

Done by "Cao, WudiX" <wudix.cao@intel.com>

**Review by wudicaox — COMMENTED** [review]
Failure when executing preintegration builder

FAILURE:cancelled Generate multi manifest original json

More details, logs, and binaries: /absp-wudicaox_test/builders/for_integration_tests_android_github-preintegration/builds/130

**Review by wudicaox — COMMENTED** [review]
PR integrated into 'preintegration' builder



More details, logs, and binaries: /absp-wudicaox_test/builders/for_integration_tests_android_github-preintegration/builds/131

Done by "Cao, WudiX" <wudix.cao@intel.com>

**Review by wudicaox — COMMENTED** [review]
PR integrated into 'premerge' builder



More details, logs, and binaries: /absp-wudicaox_test/builders/for_integration_tests_android_github-premerge/builds/95

Done by "Cao, WudiX" <wudix.cao@intel.com>

**Review by wudicaox — COMMENTED** [review]
PR integrated into 'preintegration' builder



More details, logs, and binaries: /absp-wudicaox_test/builders/for_integration_tests_android_github-preintegration/builds/139

Done by "Cao, WudiX" <wudix.cao@intel.com>

**Review by wudicaox — COMMENTED** [review]
PR integrated into 'premerge' builder



More details, logs, and binaries: /absp-wudicaox_test/builders/for_integration_tests_android_github-premerge/builds/100

Done by "Cao, WudiX" <wudix.cao@intel.com>

**Review by wudicaox — COMMENTED** [review]
PR integrated into 'preintegration' builder



More details, logs, and binaries: /absp-wudicaox_test/builders/for_integration_tests_android_github-preintegration/builds/140

Done by "Cao, WudiX" <wudix.cao@intel.com>

**Review by wudicaox — COMMENTED** [review]
PR integrated into 'premerge' builder



More details, logs, and binaries: /absp-wudicaox_test/builders/for_integration_tests_android_github-premerge/builds/101

Done by "Cao, WudiX" <wudix.cao@intel.com>

**Review by wudicaox — COMMENTED** [review]
Failure when executing preintegration builder

FAILURE:Clean output Creating dir: build/pub ...

More details, logs, and binaries: /absp-wudicaox_test/builders/for_integration_tests_android_github-preintegration/builds/141

**Review by wudicaox — COMMENTED** [review]
Failure when executing preintegration builder

FAILURE:Clean output Creating dir: build/pub ...

More details, logs, and binaries: /absp-wudicaox_test/builders/for_integration_tests_android_github-preintegration/builds/142

**Review by wudicaox — COMMENTED** [review]
PR integrated into 'preintegration' builder



More details, logs, and binaries: /absp-wudicaox_test/builders/for_integration_tests_android_github-preintegration/builds/143

Done by "Cao, WudiX" <wudix.cao@intel.com>

**Review by wudicaox — COMMENTED** [review]
Failure when executing preintegration builder

FAILURE:Clean output Creating dir: build/pub ...

More details, logs, and binaries: /absp-wudicaox_test/builders/for_integration_tests_android_github-preintegration/builds/144

**Review by wudicaox — COMMENTED** [review]
Failure when executing preintegration builder

FAILURE:Clean output Creating dir: build/pub ...

More details, logs, and binaries: /absp-wudicaox_test/builders/for_integration_tests_android_github-preintegration/builds/145

**Review by wudicaox — COMMENTED** [review]
Failure when executing preintegration builder

FAILURE:Clean output Creating dir: build/pub ...

More details, logs, and binaries: /absp-wudicaox_test/builders/for_integration_tests_android_github-preintegration/builds/146

**Review by wudicaox — COMMENTED** [review]
Failure when executing preintegration builder

FAILURE:Clean output Creating dir: build/pub ...

More details, logs, and binaries: /absp-wudicaox_test/builders/for_integration_tests_android_github-preintegration/builds/147

**Review by wudicaox — COMMENTED** [review]
PR integrated into 'preintegration' builder

Your build ended in WARNING state. Please promote it carefully



More details, logs, and binaries: /absp-wudicaox_test/builders/for_integration_tests_android_github-preintegration/builds/148

Done by "Cao, WudiX" <wudix.cao@intel.com>

**Review by wudicaox — COMMENTED** [review]
Failure when executing preintegration builder

FAILURE:Clean output Creating dir: build/pub ...

More details, logs, and binaries: /absp-wudicaox_test/builders/for_integration_tests_android_github-preintegration/builds/149

**Review by wudicaox — COMMENTED** [review]
PR integrated into 'preintegration' builder

Your build ended in WARNING state. Please promote it carefully



More details, logs, and binaries: /absp-wudicaox_test/builders/for_integration_tests_android_github-preintegration/builds/150

Done by "Cao, WudiX" <wudix.cao@intel.com>

**Pull request closed without merging**
