### PR TITLE
test1

### PR DESCRIPTION
**Pull request by wudicaox**
Tracked-On: OAM-66854
Signed-off-by: wudicaox <wudix.cao@intel.com>

### CODE REVIEW

**Review by 745631453 — APPROVED** [review]
ok

**Review by wudicaox — COMMENTED** [review]
Failure when executing preintegration builder

FAILURE:CheckApprovals Generate multi manifest original json

More details, logs, and binaries: /absp-wudicaox_test/builders/for_integration_tests_android_github-preintegration/builds/12

**Review by wudicaox — COMMENTED** [review]
Failure when executing preintegration builder

FAILURE:Trigger Builds Triggered: build-for_integration_tests - r1 (r1_target1), build-for_integration_tests - r2 (r2_target1), build-for_integration_tests - r2 (r2_target2)

More details, logs, and binaries: /absp-wudicaox_test/builders/for_integration_tests_android_github-preintegration/builds/13

**Review by wudicaox — COMMENTED** [review]
PR integrated into 'preintegration' builder



More details, logs, and binaries: /absp-wudicaox_test/builders/for_integration_tests_android_github-preintegration/builds/14

Done by "Cao, WudiX" <wudix.cao@intel.com>

**Review by wudicaox — COMMENTED** [review]
Failure when executing preintegration builder

FAILURE: CheckBug Bad comments/Bugs

More details, logs, and binaries: /absp-wudicaox_test/builders/for_integration_tests_android_github-premerge/builds/3

**Review by wudicaox — COMMENTED** [review]
PR integrated into 'preintegration' builder



More details, logs, and binaries: /absp-wudicaox_test/builders/for_integration_tests_android_github-preintegration/builds/15

Done by "Cao, WudiX" <wudix.cao@intel.com>

**Review by wudicaox — COMMENTED** [review]
PR integrated into 'premerge' builder



More details, logs, and binaries: /absp-wudicaox_test/builders/for_integration_tests_android_github-premerge/builds/4

Done by "Cao, WudiX" <wudix.cao@intel.com>

**Review by wudicaox — COMMENTED** [review]
PR integrated into 'preintegration' builder



More details, logs, and binaries: /absp-wudicaox_test/builders/for_integration_tests_android_github-preintegration/builds/16

Done by "Cao, WudiX" <wudix.cao@intel.com>

**Review by wudicaox — COMMENTED** [review]
PR integrated into 'premerge' builder



More details, logs, and binaries: /absp-wudicaox_test/builders/for_integration_tests_android_github-premerge/builds/5

Done by "Cao, WudiX" <wudix.cao@intel.com>

**Pull request closed without merging**
