### PR TITLE
test for dev sprint6.12_4

### PR DESCRIPTION
**Pull request by shenya1x**
Tracked-On: OAM-66547
Signed-off-by: shenya1x <yangx.shen@intel.com>

### CODE REVIEW

**Review by opencistage — APPROVED** [review]

**Review by shenya1x — COMMENTED** [review]
Autobuild started from pull-request-approved on this PR.

FAILURE: CheckBug Bad comments/Bugs

For more information, see: /absp-shenya1x_test/builders/for_integration_tests_android_github-autobuild/builds/54

**Review by shenya1x — COMMENTED** [review]
Autobuild started from pull-request-approved on this PR.

Cactus automatically verified this PR.

For more information, see: /absp-shenya1x_test/builders/for_integration_tests_android_github-autobuild/builds/55

**Review by shenya1x — COMMENTED** [review]
Autobuild started from pull-request-approved on this PR.

Cactus automatically verified this PR.

For more information, see: /absp-shenya1x_test/builders/for_integration_tests_android_github-autobuild/builds/56

**Review by shenya1x — COMMENTED** [review]
Autobuild started from pull-request-approved on this PR.

FAILURE: CheckBug Bad comments/Bugs

For more information, see: /absp-shenya1x_test/builders/for_integration_tests_android_github-autobuild/builds/57

**Review by shenya1x — COMMENTED** [review]
Failure when executing preintegration builder

FAILURE:CheckBug Bad comments/Bugs

More details, logs, and binaries: /absp-shenya1x_test/builders/for_integration_tests_android_github-preintegration/builds/47

**Review by shenya1x — COMMENTED** [review]
PR integrated into 'preintegration' builder



More details, logs, and binaries: /absp-shenya1x_test/builders/for_integration_tests_android_github-preintegration/builds/48

Done by "Shen, YangX" <yangx.shen@intel.com>

**Review by shenya1x — COMMENTED** [review]
PR integrated into 'premerge' builder



More details, logs, and binaries: /absp-shenya1x_test/builders/for_integration_tests_android_github-premerge/builds/23

Done by "Shen, YangX" <yangx.shen@intel.com>

**Review by shenya1x — COMMENTED** [review]
cactus finished building and testing your PR 

It was requested for merge by "Shen, YangX" <yangx.shen@intel.com> 

so we merge it. Thanks for your contribution.

more details, logs, and binaries: /absp-shenya1x_test/builders/for_integration_tests_android_github-mergerequest/builds/25

**Pull request merged**
