### PR TITLE
test3

### PR DESCRIPTION
**Pull request by wudicaox**
Tracked-On: OAM-66907
Signed-off-by: wudicaox <wudix.cao@intel.com>

### CODE REVIEW

**Review by 745631453 — APPROVED** [review]
ok

**Review by wudicaox — COMMENTED** [review]
PR integrated into 'preintegration' builder



More details, logs, and binaries: /absp-wudicaox_test/builders/for_integration_tests_android_github-preintegration/builds/19

Done by "Cao, WudiX" <wudix.cao@intel.com>

**Review by wudicaox — COMMENTED** [review]
PR integrated into 'premerge' builder



More details, logs, and binaries: /absp-wudicaox_test/builders/for_integration_tests_android_github-premerge/builds/7

Done by "Cao, WudiX" <wudix.cao@intel.com>

**Review by wudicaox — COMMENTED** [review]
PR integrated into 'preintegration' builder



More details, logs, and binaries: /absp-wudicaox_test/builders/for_integration_tests_android_github-preintegration/builds/22

Done by "Cao, WudiX" <wudix.cao@intel.com>

**Review by wudicaox — COMMENTED** [review]
PR integrated into 'premerge' builder



More details, logs, and binaries: /absp-wudicaox_test/builders/for_integration_tests_android_github-premerge/builds/9

Done by "Cao, WudiX" <wudix.cao@intel.com>

**Review by wudicaox — COMMENTED** [review]
PR integrated into 'preintegration' builder



More details, logs, and binaries: /absp-wudicaox_test/builders/for_integration_tests_android_github-preintegration/builds/25

Done by "Cao, WudiX" <wudix.cao@intel.com>

**Review by wudicaox — COMMENTED** [review]
PR integrated into 'premerge' builder



More details, logs, and binaries: /absp-wudicaox_test/builders/for_integration_tests_android_github-premerge/builds/14

Done by "Cao, WudiX" <wudix.cao@intel.com>

**Review by wudicaox — COMMENTED** [review]
PR integrated into 'preintegration' builder



More details, logs, and binaries: /absp-wudicaox_test/builders/for_integration_tests_android_github-preintegration/builds/28

Done by "Cao, WudiX" <wudix.cao@intel.com>

**Review by wudicaox — COMMENTED** [review]
PR integrated into 'premerge' builder



More details, logs, and binaries: /absp-wudicaox_test/builders/for_integration_tests_android_github-premerge/builds/16

Done by "Cao, WudiX" <wudix.cao@intel.com>

**Review by wudicaox — COMMENTED** [review]
PR integrated into 'preintegration' builder



More details, logs, and binaries: /absp-wudicaox_test/builders/for_integration_tests_android_github-preintegration/builds/31

Done by "Cao, WudiX" <wudix.cao@intel.com>

**Review by wudicaox — COMMENTED** [review]
PR integrated into 'premerge' builder



More details, logs, and binaries: /absp-wudicaox_test/builders/for_integration_tests_android_github-premerge/builds/19

Done by "Cao, WudiX" <wudix.cao@intel.com>

**Review by wudicaox — COMMENTED** [review]
PR integrated into 'preintegration' builder



More details, logs, and binaries: /absp-wudicaox_test/builders/for_integration_tests_android_github-preintegration/builds/34

Done by "Cao, WudiX" <wudix.cao@intel.com>

**Review by wudicaox — COMMENTED** [review]
PR integrated into 'premerge' builder



More details, logs, and binaries: /absp-wudicaox_test/builders/for_integration_tests_android_github-premerge/builds/23

Done by "Cao, WudiX" <wudix.cao@intel.com>

**Review by wudicaox — COMMENTED** [review]
PR integrated into 'preintegration' builder



More details, logs, and binaries: /absp-wudicaox_test/builders/for_integration_tests_android_github-preintegration/builds/37

Done by "Cao, WudiX" <wudix.cao@intel.com>

**Review by wudicaox — COMMENTED** [review]
PR integrated into 'premerge' builder



More details, logs, and binaries: /absp-wudicaox_test/builders/for_integration_tests_android_github-premerge/builds/26

Done by "Cao, WudiX" <wudix.cao@intel.com>

**Review by wudicaox — COMMENTED** [review]
PR integrated into 'preintegration' builder



More details, logs, and binaries: /absp-wudicaox_test/builders/for_integration_tests_android_github-preintegration/builds/40

Done by "Cao, WudiX" <wudix.cao@intel.com>

**Review by wudicaox — COMMENTED** [review]
PR integrated into 'premerge' builder



More details, logs, and binaries: /absp-wudicaox_test/builders/for_integration_tests_android_github-premerge/builds/28

Done by "Cao, WudiX" <wudix.cao@intel.com>

**Review by wudicaox — COMMENTED** [review]
PR integrated into 'preintegration' builder



More details, logs, and binaries: /absp-wudicaox_test/builders/for_integration_tests_android_github-preintegration/builds/43

Done by "Cao, WudiX" <wudix.cao@intel.com>

**Review by wudicaox — COMMENTED** [review]
PR integrated into 'premerge' builder



More details, logs, and binaries: /absp-wudicaox_test/builders/for_integration_tests_android_github-premerge/builds/32

Done by "Cao, WudiX" <wudix.cao@intel.com>

**Review by wudicaox — COMMENTED** [review]
PR integrated into 'preintegration' builder



More details, logs, and binaries: /absp-wudicaox_test/builders/for_integration_tests_android_github-preintegration/builds/46

Done by "Cao, WudiX" <wudix.cao@intel.com>

**Review by wudicaox — COMMENTED** [review]
PR integrated into 'premerge' builder



More details, logs, and binaries: /absp-wudicaox_test/builders/for_integration_tests_android_github-premerge/builds/35

Done by "Cao, WudiX" <wudix.cao@intel.com>

**Review by wudicaox — COMMENTED** [review]
PR integrated into 'preintegration' builder



More details, logs, and binaries: /absp-wudicaox_test/builders/for_integration_tests_android_github-preintegration/builds/49

Done by "Cao, WudiX" <wudix.cao@intel.com>

**Review by wudicaox — COMMENTED** [review]
PR integrated into 'premerge' builder



More details, logs, and binaries: /absp-wudicaox_test/builders/for_integration_tests_android_github-premerge/builds/37

Done by "Cao, WudiX" <wudix.cao@intel.com>

**Review by wudicaox — COMMENTED** [review]
PR integrated into 'preintegration' builder



More details, logs, and binaries: /absp-wudicaox_test/builders/for_integration_tests_android_github-preintegration/builds/52

Done by "Cao, WudiX" <wudix.cao@intel.com>

**Review by wudicaox — COMMENTED** [review]
PR integrated into 'premerge' builder



More details, logs, and binaries: /absp-wudicaox_test/builders/for_integration_tests_android_github-premerge/builds/41

Done by "Cao, WudiX" <wudix.cao@intel.com>

**Review by wudicaox — COMMENTED** [review]
PR integrated into 'preintegration' builder



More details, logs, and binaries: /absp-wudicaox_test/builders/for_integration_tests_android_github-preintegration/builds/55

Done by "Cao, WudiX" <wudix.cao@intel.com>

**Review by wudicaox — COMMENTED** [review]
PR integrated into 'premerge' builder



More details, logs, and binaries: /absp-wudicaox_test/builders/for_integration_tests_android_github-premerge/builds/42

Done by "Cao, WudiX" <wudix.cao@intel.com>

**Review by wudicaox — COMMENTED** [review]
PR integrated into 'preintegration' builder



More details, logs, and binaries: /absp-wudicaox_test/builders/for_integration_tests_android_github-preintegration/builds/58

Done by "Cao, WudiX" <wudix.cao@intel.com>

**Review by wudicaox — COMMENTED** [review]
PR integrated into 'premerge' builder



More details, logs, and binaries: /absp-wudicaox_test/builders/for_integration_tests_android_github-premerge/builds/45

Done by "Cao, WudiX" <wudix.cao@intel.com>

**Review by wudicaox — COMMENTED** [review]
PR integrated into 'preintegration' builder



More details, logs, and binaries: /absp-wudicaox_test/builders/for_integration_tests_android_github-preintegration/builds/61

Done by "Cao, WudiX" <wudix.cao@intel.com>

**Review by wudicaox — COMMENTED** [review]
PR integrated into 'premerge' builder



More details, logs, and binaries: /absp-wudicaox_test/builders/for_integration_tests_android_github-premerge/builds/50

Done by "Cao, WudiX" <wudix.cao@intel.com>

**Review by wudicaox — COMMENTED** [review]
PR integrated into 'preintegration' builder



More details, logs, and binaries: /absp-wudicaox_test/builders/for_integration_tests_android_github-preintegration/builds/64

Done by "Cao, WudiX" <wudix.cao@intel.com>

**Review by wudicaox — COMMENTED** [review]
PR integrated into 'premerge' builder



More details, logs, and binaries: /absp-wudicaox_test/builders/for_integration_tests_android_github-premerge/builds/53

Done by "Cao, WudiX" <wudix.cao@intel.com>

**Review by wudicaox — COMMENTED** [review]
PR integrated into 'preintegration' builder



More details, logs, and binaries: /absp-wudicaox_test/builders/for_integration_tests_android_github-preintegration/builds/67

Done by "Cao, WudiX" <wudix.cao@intel.com>

**Review by wudicaox — COMMENTED** [review]
PR integrated into 'premerge' builder



More details, logs, and binaries: /absp-wudicaox_test/builders/for_integration_tests_android_github-premerge/builds/55

Done by "Cao, WudiX" <wudix.cao@intel.com>

**Review by wudicaox — COMMENTED** [review]
PR integrated into 'preintegration' builder



More details, logs, and binaries: /absp-wudicaox_test/builders/for_integration_tests_android_github-preintegration/builds/70

Done by "Cao, WudiX" <wudix.cao@intel.com>

**Review by wudicaox — COMMENTED** [review]
PR integrated into 'premerge' builder



More details, logs, and binaries: /absp-wudicaox_test/builders/for_integration_tests_android_github-premerge/builds/57

Done by "Cao, WudiX" <wudix.cao@intel.com>

**Review by wudicaox — COMMENTED** [review]
PR integrated into 'preintegration' builder



More details, logs, and binaries: /absp-wudicaox_test/builders/for_integration_tests_android_github-preintegration/builds/73

Done by "Cao, WudiX" <wudix.cao@intel.com>

**Review by wudicaox — COMMENTED** [review]
PR integrated into 'premerge' builder



More details, logs, and binaries: /absp-wudicaox_test/builders/for_integration_tests_android_github-premerge/builds/62

Done by "Cao, WudiX" <wudix.cao@intel.com>

**Review by wudicaox — COMMENTED** [review]
PR integrated into 'preintegration' builder



More details, logs, and binaries: /absp-wudicaox_test/builders/for_integration_tests_android_github-preintegration/builds/76

Done by "Cao, WudiX" <wudix.cao@intel.com>

**Review by wudicaox — COMMENTED** [review]
PR integrated into 'premerge' builder



More details, logs, and binaries: /absp-wudicaox_test/builders/for_integration_tests_android_github-premerge/builds/65

Done by "Cao, WudiX" <wudix.cao@intel.com>

**Review by wudicaox — COMMENTED** [review]
PR integrated into 'preintegration' builder



More details, logs, and binaries: /absp-wudicaox_test/builders/for_integration_tests_android_github-preintegration/builds/79

Done by "Cao, WudiX" <wudix.cao@intel.com>

**Review by wudicaox — COMMENTED** [review]
PR integrated into 'premerge' builder



More details, logs, and binaries: /absp-wudicaox_test/builders/for_integration_tests_android_github-premerge/builds/68

Done by "Cao, WudiX" <wudix.cao@intel.com>

**Review by wudicaox — COMMENTED** [review]
PR integrated into 'preintegration' builder



More details, logs, and binaries: /absp-wudicaox_test/builders/for_integration_tests_android_github-preintegration/builds/82

Done by "Cao, WudiX" <wudix.cao@intel.com>

**Review by wudicaox — COMMENTED** [review]
PR integrated into 'premerge' builder



More details, logs, and binaries: /absp-wudicaox_test/builders/for_integration_tests_android_github-premerge/builds/71

Done by "Cao, WudiX" <wudix.cao@intel.com>

**Review by wudicaox — COMMENTED** [review]
Failure when executing preintegration builder

FAILURE:Trigger Builds Triggered: build-for_integration_tests - r1 (r1_target1) - extra, build-for_integration_tests - r1 (r2_target1), build-for_integration_tests - r1 (r2_target2)

More details, logs, and binaries: /absp-wudicaox_test/builders/for_integration_tests_android_github-preintegration/builds/85

**Review by wudicaox — COMMENTED** [review]
Failure when executing preintegration builder

FAILURE:Trigger Builds Triggered: build-for_integration_tests - r1 (r1_target1) - extra, build-for_integration_tests - r1 (r2_target1), build-for_integration_tests - r1 (r2_target2)

More details, logs, and binaries: /absp-wudicaox_test/builders/for_integration_tests_android_github-preintegration/builds/93

**Review by wudicaox — COMMENTED** [review]
Failure when executing preintegration builder

FAILURE:Trigger Builds Triggered: build-for_integration_tests - r1 (r1_target1) - extra, build-for_integration_tests - r1 (r2_target1), build-for_integration_tests - r1 (r2_target2)

More details, logs, and binaries: /absp-wudicaox_test/builders/for_integration_tests_android_github-preintegration/builds/94

**Review by wudicaox — COMMENTED** [review]
Failure when executing preintegration builder

FAILURE:Trigger Builds Triggered: build-for_integration_tests - r1 (r1_target1) - extra, build-for_integration_tests - r1 (r2_target1), build-for_integration_tests - r1 (r2_target2)

More details, logs, and binaries: /absp-wudicaox_test/builders/for_integration_tests_android_github-preintegration/builds/95

**Review by wudicaox — COMMENTED** [review]
Failure when executing preintegration builder

FAILURE:Trigger Builds Triggered: build-for_integration_tests - r1 (r1_target1) - extra, build-for_integration_tests - r1 (r2_target1), build-for_integration_tests - r1 (r2_target2)

More details, logs, and binaries: /absp-wudicaox_test/builders/for_integration_tests_android_github-preintegration/builds/96

**Review by wudicaox — COMMENTED** [review]
Failure when executing preintegration builder

FAILURE:Trigger Builds Triggered: build-for_integration_tests - r1 (r1_target1) - extra, build-for_integration_tests - r1 (r2_target1), build-for_integration_tests - r1 (r2_target2)

More details, logs, and binaries: /absp-wudicaox_test/builders/for_integration_tests_android_github-preintegration/builds/97

**Review by wudicaox — COMMENTED** [review]
Failure when executing preintegration builder

FAILURE:Trigger Builds Triggered: build-for_integration_tests - r1 (r1_target1) - extra, build-for_integration_tests - r1 (r2_target1), build-for_integration_tests - r1 (r2_target2)

More details, logs, and binaries: /absp-wudicaox_test/builders/for_integration_tests_android_github-preintegration/builds/100

**Review by wudicaox — COMMENTED** [review]
PR integrated into 'preintegration' builder



More details, logs, and binaries: /absp-wudicaox_test/builders/for_integration_tests_android_github-preintegration/builds/107

Done by "Cao, WudiX" <wudix.cao@intel.com>

**Review by wudicaox — COMMENTED** [review]
PR integrated into 'premerge' builder



More details, logs, and binaries: /absp-wudicaox_test/builders/for_integration_tests_android_github-premerge/builds/75

Done by "Cao, WudiX" <wudix.cao@intel.com>

**Review by wudicaox — COMMENTED** [review]
Failure when executing preintegration builder

FAILURE:Trigger Builds Triggered: build-for_integration_tests - r1 (r1_target1) - extra, build-for_integration_tests - r1 (r2_target1), build-for_integration_tests - r1 (r2_target2)

More details, logs, and binaries: /absp-wudicaox_test/builders/for_integration_tests_android_github-preintegration/builds/110

**Review by wudicaox — COMMENTED** [review]
PR integrated into 'preintegration' builder



More details, logs, and binaries: /absp-wudicaox_test/builders/for_integration_tests_android_github-preintegration/builds/113

Done by "Cao, WudiX" <wudix.cao@intel.com>

**Review by wudicaox — COMMENTED** [review]
PR integrated into 'premerge' builder



More details, logs, and binaries: /absp-wudicaox_test/builders/for_integration_tests_android_github-premerge/builds/78

Done by "Cao, WudiX" <wudix.cao@intel.com>

**Review by wudicaox — COMMENTED** [review]
PR integrated into 'preintegration' builder



More details, logs, and binaries: /absp-wudicaox_test/builders/for_integration_tests_android_github-preintegration/builds/116

Done by "Cao, WudiX" <wudix.cao@intel.com>

**Review by wudicaox — COMMENTED** [review]
PR integrated into 'premerge' builder



More details, logs, and binaries: /absp-wudicaox_test/builders/for_integration_tests_android_github-premerge/builds/80

Done by "Cao, WudiX" <wudix.cao@intel.com>

**Review by wudicaox — COMMENTED** [review]
PR integrated into 'preintegration' builder



More details, logs, and binaries: /absp-wudicaox_test/builders/for_integration_tests_android_github-preintegration/builds/119

Done by "Cao, WudiX" <wudix.cao@intel.com>

**Review by wudicaox — COMMENTED** [review]
PR integrated into 'premerge' builder



More details, logs, and binaries: /absp-wudicaox_test/builders/for_integration_tests_android_github-premerge/builds/84

Done by "Cao, WudiX" <wudix.cao@intel.com>

**Review by wudicaox — COMMENTED** [review]
PR integrated into 'preintegration' builder



More details, logs, and binaries: /absp-wudicaox_test/builders/for_integration_tests_android_github-preintegration/builds/122

Done by "Cao, WudiX" <wudix.cao@intel.com>

**Review by wudicaox — COMMENTED** [review]
PR integrated into 'premerge' builder



More details, logs, and binaries: /absp-wudicaox_test/builders/for_integration_tests_android_github-premerge/builds/86

Done by "Cao, WudiX" <wudix.cao@intel.com>

**Review by wudicaox — COMMENTED** [review]
PR integrated into 'preintegration' builder



More details, logs, and binaries: /absp-wudicaox_test/builders/for_integration_tests_android_github-preintegration/builds/125

Done by "Cao, WudiX" <wudix.cao@intel.com>

**Review by wudicaox — COMMENTED** [review]
PR integrated into 'premerge' builder



More details, logs, and binaries: /absp-wudicaox_test/builders/for_integration_tests_android_github-premerge/builds/90

Done by "Cao, WudiX" <wudix.cao@intel.com>

**Review by wudicaox — COMMENTED** [review]
PR integrated into 'preintegration' builder



More details, logs, and binaries: /absp-wudicaox_test/builders/for_integration_tests_android_github-preintegration/builds/128

Done by "Cao, WudiX" <wudix.cao@intel.com>

**Review by wudicaox — COMMENTED** [review]
PR integrated into 'premerge' builder



More details, logs, and binaries: /absp-wudicaox_test/builders/for_integration_tests_android_github-premerge/builds/93

Done by "Cao, WudiX" <wudix.cao@intel.com>

**Review by wudicaox — COMMENTED** [review]
PR integrated into 'preintegration' builder



More details, logs, and binaries: /absp-wudicaox_test/builders/for_integration_tests_android_github-preintegration/builds/132

Done by "Cao, WudiX" <wudix.cao@intel.com>

**Review by wudicaox — COMMENTED** [review]
PR integrated into 'premerge' builder



More details, logs, and binaries: /absp-wudicaox_test/builders/for_integration_tests_android_github-premerge/builds/96

Done by "Cao, WudiX" <wudix.cao@intel.com>

**Pull request closed without merging**
