### PR TITLE
test for dev sprint 6.12_3

### PR DESCRIPTION
**Pull request by shenya1x**
Tracked-On: OAM-66547
Signed-off-by: shenya1x <yangx.shen@intel.com>

### CODE REVIEW

**Review by shenya1x — COMMENTED** [review]
Failure when executing preintegration builder

FAILURE:CheckApprovals Some checks are failed. See the step results.html

More details, logs, and binaries: /absp-shenya1x_test/builders/for_integration_tests_android_github-preintegration/builds/30

**Review by forintegrationtests — APPROVED** [review]

**Review by shenya1x — COMMENTED** [review]
PR integrated into 'preintegration' builder



More details, logs, and binaries: /absp-shenya1x_test/builders/for_integration_tests_android_github-preintegration/builds/31

Done by "Shen, YangX" <yangx.shen@intel.com>

**Review by shenya1x — COMMENTED** [review]
Autobuild started from pull-request-approved on this PR.

Cactus automatically verified this PR.

For more information, see: /absp-shenya1x_test/builders/for_integration_tests_android_github-autobuild/builds/46

**Review by shenya1x — COMMENTED** [review]
PR integrated into 'preintegration' builder



More details, logs, and binaries: /absp-shenya1x_test/builders/for_integration_tests_android_github-preintegration/builds/33

Done by "Shen, YangX" <yangx.shen@intel.com>

**Review by shenya1x — COMMENTED** [review]
PR integrated into 'premerge' builder



More details, logs, and binaries: /absp-shenya1x_test/builders/for_integration_tests_android_github-premerge/builds/12

Done by "Shen, YangX" <yangx.shen@intel.com>

**Review by shenya1x — COMMENTED** [review]
PR integrated into 'preintegration' builder



More details, logs, and binaries: /absp-shenya1x_test/builders/for_integration_tests_android_github-preintegration/builds/42

Done by "Shen, YangX" <yangx.shen@intel.com>

**Review by shenya1x — COMMENTED** [review]
Failure when executing preintegration builder

FAILURE:CheckBug Bad comments/Bugs

More details, logs, and binaries: /absp-shenya1x_test/builders/for_integration_tests_android_github-preintegration/builds/43

**Review by shenya1x — COMMENTED** [review]
PR integrated into 'preintegration' builder



More details, logs, and binaries: /absp-shenya1x_test/builders/for_integration_tests_android_github-preintegration/builds/44

Done by "Shen, YangX" <yangx.shen@intel.com>

**Review by shenya1x — COMMENTED** [review]
cactus finished building and testing your PR 

It was requested for merge by "Shen, YangX" <yangx.shen@intel.com> 

so we merge it. Thanks for your contribution.

more details, logs, and binaries: /absp-shenya1x_test/builders/for_integration_tests_android_github-mergerequest/builds/16

**Review by shenya1x — COMMENTED** [review]
cactus finished building and testing your PR 

It was requested for merge by "Shen, YangX" <yangx.shen@intel.com> 

so we merge it. Thanks for your contribution.

more details, logs, and binaries: /absp-shenya1x_test/builders/for_integration_tests_android_github-mergerequest/builds/17

**Review by shenya1x — COMMENTED** [review]
cactus finished building and testing your PR 

It was requested for merge by "Shen, YangX" <yangx.shen@intel.com> 

so we merge it. Thanks for your contribution.

more details, logs, and binaries: /absp-shenya1x_test/builders/for_integration_tests_android_github-mergerequest/builds/18

**Review by shenya1x — COMMENTED** [review]
PR integrated into 'premerge' builder



More details, logs, and binaries: /absp-shenya1x_test/builders/for_integration_tests_android_github-premerge/builds/19

Done by "Shen, YangX" <yangx.shen@intel.com>

**Review by shenya1x — COMMENTED** [review]
PR integrated into 'premerge' builder



More details, logs, and binaries: /absp-shenya1x_test/builders/for_integration_tests_android_github-premerge/builds/20

Done by "Shen, YangX" <yangx.shen@intel.com>

**Review by shenya1x — COMMENTED** [review]
Autobuild started from pull-request-approved on this PR.

FAILURE: CheckBug Bad comments/Bugs

For more information, see: /absp-shenya1x_test/builders/for_integration_tests_android_github-autobuild/builds/51

**Review by shenya1x — COMMENTED** [review]
PR integrated into 'preintegration' builder



More details, logs, and binaries: /absp-shenya1x_test/builders/for_integration_tests_android_github-preintegration/builds/45

Done by "Shen, YangX" <yangx.shen@intel.com>

**Review by shenya1x — COMMENTED** [review]
Failure when executing preintegration builder

FAILURE: ComputeDependencies The list of pull requests (projectName/pullreq_id/sha) is different than the one in the preintegration.
Errors:
  the following changes [(u'forintegrationtests/OpenSSL', 19)] were not in the pre-merge build

More details, logs, and binaries: /absp-shenya1x_test/builders/for_integration_tests_android_github-premerge/builds/21

**Review by shenya1x — COMMENTED** [review]
Failure when executing preintegration builder

FAILURE:CheckBug Bad comments/Bugs

More details, logs, and binaries: /absp-shenya1x_test/builders/for_integration_tests_android_github-preintegration/builds/46

**Review by shenya1x — COMMENTED** [review]
Failure when executing preintegration builder

FAILURE: CheckBug Bad comments/Bugs

More details, logs, and binaries: /absp-shenya1x_test/builders/for_integration_tests_android_github-premerge/builds/22

**Review by shenya1x — COMMENTED** [review]
cactus finished building and testing your PR 

It was requested for merge by "Shen, YangX" <yangx.shen@intel.com> 

so we merge it. Thanks for your contribution.

more details, logs, and binaries: /absp-shenya1x_test/builders/for_integration_tests_android_github-mergerequest/builds/22

**Pull request merged**
