### PR TITLE
test for dev sprint 6.12_1

### PR DESCRIPTION
**Pull request by shenya1x**
Tracked-On: OAM-66547
Signed-off-by: shenya1x <yangx.shen@intel.com>

### CODE REVIEW

**Review by forintegrationtests — APPROVED** [review]

**Review by shenya1x — COMMENTED** [review]
Autobuild started from aaa on this PR.

Cactus automatically verified this PR.

For more information, see: bbb

**Review by shenya1x — COMMENTED** [review]
Autobuild started from pull-request-approved on this PR.

Cactus automatically verified this PR.

For more information, see: /absp-shenya1x_test/builders/for_integration_tests_android_github-autobuild/builds/21

**Review by shenya1x — COMMENTED** [review]
Autobuild started from pull-request-approved on this PR.

FAILURE:None

For more information, see: None

**Review by shenya1x — COMMENTED** [review]
Autobuild started from pull-request-approved on this PR.

FAILURE:['CheckBug', 'Bad comments/Bugs']

For more information, see: None

**Review by shenya1x — COMMENTED** [review]
Autobuild started from pull-request-approved on this PR.

FAILURE:CheckBugBad comments/Bugs

For more information, see: /absp-shenya1x_test/builders/for_integration_tests_android_github-autobuild/builds/36

**Review by shenya1x — COMMENTED** [review]
Autobuild started from pull-request-approved on this PR.

FAILURE:CheckBug Bad comments/Bugs

For more information, see: /absp-shenya1x_test/builders/for_integration_tests_android_github-autobuild/builds/38

**Review by shenya1x — COMMENTED** [review]
Failure when executing preintegration builder

More details, logs, and binaries: /absp-shenya1x_test/builders/for_integration_tests_android_github-preintegration/builds/5

**Review by shenya1x — COMMENTED** [review]
Autobuild started from pull-request-approved on this PR.

FAILURE:CheckBug Bad comments/Bugs

For more information, see: /absp-shenya1x_test/builders/for_integration_tests_android_github-autobuild/builds/39

**Review by shenya1x — COMMENTED** [review]
Failure when executing preintegration builder

FAILURE:CheckBug Bad comments/Bugs

More details, logs, and binaries: /absp-shenya1x_test/builders/for_integration_tests_android_github-preintegration/builds/6

**Review by forintegrationtests — CHANGES_REQUESTED** [review]
request changes

**Review by shenya1x — COMMENTED** [review]
Failure when executing preintegration builder

FAILURE:CheckApprovals Some checks are failed. See the step results.html

More details, logs, and binaries: /absp-shenya1x_test/builders/for_integration_tests_android_github-preintegration/builds/7

**Review by shenya1x — COMMENTED** [review]
Failure when executing preintegration builder

FAILURE:CheckApprovals Good approvals

More details, logs, and binaries: /absp-shenya1x_test/builders/for_integration_tests_android_github-preintegration/builds/8

**Review by shenya1x — COMMENTED** [review]
Failure when executing preintegration builder

FAILURE:CheckApprovals Good approvals

More details, logs, and binaries: /absp-shenya1x_test/builders/for_integration_tests_android_github-preintegration/builds/9

**Review by shenya1x — COMMENTED** [review]
PR integrated into 'preintegration' builder

Your build ended in WARNING state. Please promote it carefully



More details, logs, and binaries:/absp-shenya1x_test/builders/for_integration_tests_android_github-preintegration/builds/10

Done by "Shen, YangX" <yangx.shen@intel.com>

**Review by forintegrationtests — APPROVED** [review]

**Review by shenya1x — COMMENTED** [review]
PR integrated into 'preintegration' builder



More details, logs, and binaries:/absp-shenya1x_test/builders/for_integration_tests_android_github-preintegration/builds/11

Done by "Shen, YangX" <yangx.shen@intel.com>

**Review by shenya1x — COMMENTED** [review]
Autobuild started from pull-request-approved on this PR.

Cactus automatically verified this PR.

For more information, see: /absp-shenya1x_test/builders/for_integration_tests_android_github-autobuild/builds/40

**Review by shenya1x — COMMENTED** [review]
PR integrated into 'preintegration' builder



More details, logs, and binaries:/absp-shenya1x_test/builders/for_integration_tests_android_github-preintegration/builds/12

Done by "Shen, YangX" <yangx.shen@intel.com>

**Review by shenya1x — COMMENTED** [review]
PR integrated into 'preintegration' builder



More details, logs, and binaries: /absp-shenya1x_test/builders/for_integration_tests_android_github-preintegration/builds/13

Done by "Shen, YangX" <yangx.shen@intel.com>

**Review by shenya1x — COMMENTED** [review]
Failure when executing preintegration builder

FAILURE:Trigger Builds Triggered: build-for_integration_tests - r1 (r1_target1), build-for_integration_tests - r2 (r2_target1), build-for_integration_tests - r2 (r2_target2)

More details, logs, and binaries: /absp-shenya1x_test/builders/for_integration_tests_android_github-preintegration/builds/14

**Review by shenya1x — COMMENTED** [review]
Autobuild started from pull-request-approved on this PR.

Cactus automatically verified this PR.

For more information, see: /absp-shenya1x_test/builders/for_integration_tests_android_github-autobuild/builds/43

**Review by shenya1x — COMMENTED** [review]
PR integrated into 'preintegration' builder



More details, logs, and binaries: /absp-shenya1x_test/builders/for_integration_tests_android_github-preintegration/builds/15

Done by "Shen, YangX" <yangx.shen@intel.com>

**Review by shenya1x — COMMENTED** [review]
Failure when executing preintegration builder

FAILURE: ComputeDependencies The list of pull requests (projectName/pullreq_id/sha) is different than the one in the preintegration.
Errors:
  the following changes [(u'forintegrationtests/OpenSSL', 17)] were not in the pre-merge build

More details, logs, and binaries: /absp-shenya1x_test/builders/for_integration_tests_android_github-premerge/builds/1

**Review by shenya1x — COMMENTED** [review]
PR integrated into 'premerge' builder



More details, logs, and binaries: /absp-shenya1x_test/builders/for_integration_tests_android_github-premerge/builds/2

Done by "Shen, YangX" <yangx.shen@intel.com>

**Review by shenya1x — COMMENTED** [review]
PR integrated into 'preintegration' builder



More details, logs, and binaries: /absp-shenya1x_test/builders/for_integration_tests_android_github-preintegration/builds/16

Done by "Shen, YangX" <yangx.shen@intel.com>

**Review by shenya1x — COMMENTED** [review]
Failure when executing preintegration builder

FAILURE: ComputeDependencies The list of pull requests (projectName/pullreq_id/sha) is different than the one in the preintegration.
Errors:
  the following changes [(u'forintegrationtests/OpenSSL', 17)] were not in the pre-merge build

More details, logs, and binaries: /absp-shenya1x_test/builders/for_integration_tests_android_github-premerge/builds/3

**Review by shenya1x — COMMENTED** [review]
PR integrated into 'preintegration' builder



More details, logs, and binaries: /absp-shenya1x_test/builders/for_integration_tests_android_github-preintegration/builds/17

Done by "Shen, YangX" <yangx.shen@intel.com>

**Review by shenya1x — COMMENTED** [review]
Failure when executing preintegration builder

FAILURE: ComputeDependencies The list of pull requests (projectName/pullreq_id/sha) is different than the one in the preintegration.
Errors:
  the following changes [(u'forintegrationtests/OpenSSL', 17)] were not in the pre-merge build

More details, logs, and binaries: /absp-shenya1x_test/builders/for_integration_tests_android_github-premerge/builds/4

**Review by shenya1x — COMMENTED** [review]
PR integrated into 'preintegration' builder



More details, logs, and binaries: /absp-shenya1x_test/builders/for_integration_tests_android_github-preintegration/builds/18

Done by "Shen, YangX" <yangx.shen@intel.com>

**Review by shenya1x — COMMENTED** [review]
Failure when executing preintegration builder

FAILURE: ComputeDependencies The list of pull requests (projectName/pullreq_id/sha) is different than the one in the preintegration.
Errors:
  the following changes [(u'forintegrationtests/OpenSSL', 17)] were not in the pre-merge build

More details, logs, and binaries: /absp-shenya1x_test/builders/for_integration_tests_android_github-premerge/builds/5

**Review by shenya1x — COMMENTED** [review]
PR integrated into 'premerge' builder



More details, logs, and binaries: /absp-shenya1x_test/builders/for_integration_tests_android_github-premerge/builds/6

Done by "Shen, YangX" <yangx.shen@intel.com>

**Review by shenya1x — COMMENTED** [review]
PR integrated into 'preintegration' builder



More details, logs, and binaries: /absp-shenya1x_test/builders/for_integration_tests_android_github-preintegration/builds/19

Done by "Shen, YangX" <yangx.shen@intel.com>

**Review by shenya1x — COMMENTED** [review]
PR integrated into 'premerge' builder



More details, logs, and binaries: /absp-shenya1x_test/builders/for_integration_tests_android_github-premerge/builds/7

Done by "Shen, YangX" <yangx.shen@intel.com>

**Review by shenya1x — COMMENTED** [review]
cactus finished building and testing your PR 

It was requested for merge by "Shen, YangX" <yangx.shen@intel.com> 

so we merge it. Thanks for your contribution.

more details, logs, and binaries: /absp-shenya1x_test/builders/for_integration_tests_android_github-mergerequest/builds/6

**Pull request merged**
