### PR TITLE
test for dev sprint 6.12_2

### PR DESCRIPTION
**Pull request by shenya1x**
Tracked-On: OAM-66547
Signed-off-by: shenya1x <yangx.shen@intel.com>

### CODE REVIEW

**Review by forintegrationtests — APPROVED** [review]

**Review by shenya1x — COMMENTED** [review]
Autobuild started from pull-request-approved on this PR.

Cactus automatically verified this PR.

For more information, see: /absp-shenya1x_test/builders/for_integration_tests_android_github-autobuild/builds/44

**Review by shenya1x — COMMENTED** [review]
Autobuild started from pull-request-approved on this PR.

FAILURE: Trigger Builds Triggered: build-for_integration_tests - r1 (r1_target1), build-for_integration_tests - r2 (r2_target2)

For more information, see: /absp-shenya1x_test/builders/for_integration_tests_android_github-autobuild/builds/45

**Review by shenya1x — COMMENTED** [review]
PR integrated into 'preintegration' builder



More details, logs, and binaries: /absp-shenya1x_test/builders/for_integration_tests_android_github-preintegration/builds/20

Done by "Shen, YangX" <yangx.shen@intel.com>

**Review by shenya1x — COMMENTED** [review]
PR integrated into 'premerge' builder



More details, logs, and binaries: /absp-shenya1x_test/builders/for_integration_tests_android_github-premerge/builds/8

Done by "Shen, YangX" <yangx.shen@intel.com>

**Review by shenya1x — COMMENTED** [review]
Failure when executing preintegration builder

FAILURE:Trigger Builds Triggered: build-for_integration_tests - r1 (r1_target1), build-for_integration_tests - r2 (r2_target1), build-for_integration_tests - r2 (r2_target2)

More details, logs, and binaries: /absp-shenya1x_test/builders/for_integration_tests_android_github-preintegration/builds/21

**Review by shenya1x — COMMENTED** [review]
Failure when executing preintegration builder

FAILURE: CheckBug Bad comments/Bugs

More details, logs, and binaries: /absp-shenya1x_test/builders/for_integration_tests_android_github-premerge/builds/9

**Review by shenya1x — COMMENTED** [review]
Failure when executing preintegration builder

FAILURE:CheckBug Bad comments/Bugs

More details, logs, and binaries: /absp-shenya1x_test/builders/for_integration_tests_android_github-preintegration/builds/22

**Review by shenya1x — COMMENTED** [review]
Failure when executing preintegration builder

FAILURE:CheckBug Bad comments/Bugs

More details, logs, and binaries: /absp-shenya1x_test/builders/for_integration_tests_android_github-preintegration/builds/23

**Review by shenya1x — COMMENTED** [review]
Failure when executing preintegration builder

FAILURE:CheckBug Bad comments/Bugs

More details, logs, and binaries: /absp-shenya1x_test/builders/for_integration_tests_android_github-preintegration/builds/24

**Review by shenya1x — COMMENTED** [review]
Failure when executing preintegration builder

FAILURE:CheckBug Bad comments/Bugs

More details, logs, and binaries: /absp-shenya1x_test/builders/for_integration_tests_android_github-preintegration/builds/25

**Review by shenya1x — COMMENTED** [review]
PR integrated into 'preintegration' builder



More details, logs, and binaries: /absp-shenya1x_test/builders/for_integration_tests_android_github-preintegration/builds/26

Done by "Shen, YangX" <yangx.shen@intel.com>

**Review by shenya1x — COMMENTED** [review]
PR integrated into 'premerge' builder



More details, logs, and binaries: /absp-shenya1x_test/builders/for_integration_tests_android_github-premerge/builds/10

Done by "Shen, YangX" <yangx.shen@intel.com>

**Review by shenya1x — COMMENTED** [review]
PR integrated into 'preintegration' builder



More details, logs, and binaries: /absp-shenya1x_test/builders/for_integration_tests_android_github-preintegration/builds/27

Done by "Shen, YangX" <yangx.shen@intel.com>

**Review by shenya1x — COMMENTED** [review]
PR integrated into 'premerge' builder



More details, logs, and binaries: /absp-shenya1x_test/builders/for_integration_tests_android_github-premerge/builds/11

Done by "Shen, YangX" <yangx.shen@intel.com>

**Review by shenya1x — COMMENTED** [review]
cactus finished building and testing your PR 

It was requested for merge by "Shen, YangX" <yangx.shen@intel.com> 

so we merge it. Thanks for your contribution.

more details, logs, and binaries: /absp-shenya1x_test/builders/for_integration_tests_android_github-mergerequest/builds/11

**Pull request merged**
